### ISSUE TITLE
add Map

### ISSUE THREAD

**Issue by PaperMonoid** [PaperMonoid/mutau#1]
There should be a Map interface for collections with non duplicate elements. This would make existing implementations such as BinarySearchTree and RedBlackTree more useful for different use cases instead of just MultiMap.

## TODO
* [ ] Add a Map interface.
* [ ] Refactor BinarySearchTree to be a Map.
* [ ] Refactor RedBlackTree to be a Map.
* [ ] Create a Map factory.
* [ ] Refactor MultiMap implementation of BinarySearchTree.
* [ ] Refactor MultiMap implementation of RedBlackTree.
* [ ] Create a MultiMap factory.
